services:
  backend:
    container_name: backend
    build:
      target: dev
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - ./:/app
    user: 1000:1000
    depends_on:
      - db
    entrypoint: >
      sh -c "
        npx wait-port db:3306
        npm run migration:run &&
        npm run start:dev
      " 
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: teste_casal
      DB_USER: root
      DB_PASSWORD: root
      DB_POOL_LIMIT: 10
      SECRET_TOKEN: secret_token_api

  db:
    image: mysql:8.4.2
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste_casal
